name: cat_facts_app
description: A simple Cat Facts application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.1.0
  intl: ^0.20.2
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.5
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.2.2
  json_serializable: ^6.7.10

flutter_intl:
  enabled: true
  class_name: "AppLocalizations"
  main_locale: "en"
  arb_dir: "lib/l10n"
  output_dir: "lib/generated"
  use_deferred_loading: false

flutter:
  uses-material-design: true
  generate: true
